// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pdftohtml.proto

#include "pdftohtml.pb.h"
#include "pdftohtml.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace pdftohtml {

static const char* ConvertPdfToHtml_method_names[] = {
  "/pdftohtml.ConvertPdfToHtml/PdfToHtml",
};

std::unique_ptr< ConvertPdfToHtml::Stub> ConvertPdfToHtml::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ConvertPdfToHtml::Stub> stub(new ConvertPdfToHtml::Stub(channel, options));
  return stub;
}

ConvertPdfToHtml::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_PdfToHtml_(ConvertPdfToHtml_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ConvertPdfToHtml::Stub::PdfToHtml(::grpc::ClientContext* context, const ::pdftohtml::Request& request, ::pdftohtml::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::pdftohtml::Request, ::pdftohtml::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PdfToHtml_, context, request, response);
}

void ConvertPdfToHtml::Stub::async::PdfToHtml(::grpc::ClientContext* context, const ::pdftohtml::Request* request, ::pdftohtml::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::pdftohtml::Request, ::pdftohtml::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PdfToHtml_, context, request, response, std::move(f));
}

void ConvertPdfToHtml::Stub::async::PdfToHtml(::grpc::ClientContext* context, const ::pdftohtml::Request* request, ::pdftohtml::Reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PdfToHtml_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pdftohtml::Reply>* ConvertPdfToHtml::Stub::PrepareAsyncPdfToHtmlRaw(::grpc::ClientContext* context, const ::pdftohtml::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pdftohtml::Reply, ::pdftohtml::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PdfToHtml_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pdftohtml::Reply>* ConvertPdfToHtml::Stub::AsyncPdfToHtmlRaw(::grpc::ClientContext* context, const ::pdftohtml::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPdfToHtmlRaw(context, request, cq);
  result->StartCall();
  return result;
}

ConvertPdfToHtml::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ConvertPdfToHtml_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ConvertPdfToHtml::Service, ::pdftohtml::Request, ::pdftohtml::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ConvertPdfToHtml::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pdftohtml::Request* req,
             ::pdftohtml::Reply* resp) {
               return service->PdfToHtml(ctx, req, resp);
             }, this)));
}

ConvertPdfToHtml::Service::~Service() {
}

::grpc::Status ConvertPdfToHtml::Service::PdfToHtml(::grpc::ServerContext* context, const ::pdftohtml::Request* request, ::pdftohtml::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace pdftohtml

