// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pdftohtml.proto
#ifndef GRPC_pdftohtml_2eproto__INCLUDED
#define GRPC_pdftohtml_2eproto__INCLUDED

#include "pdftohtml.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace pdftohtml {

// The greeting service definition.
class ConvertPdfToHtml final {
 public:
  static constexpr char const* service_full_name() {
    return "pdftohtml.ConvertPdfToHtml";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status PdfToHtml(::grpc::ClientContext* context, const ::pdftohtml::Request& request, ::pdftohtml::Reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pdftohtml::Reply>> AsyncPdfToHtml(::grpc::ClientContext* context, const ::pdftohtml::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pdftohtml::Reply>>(AsyncPdfToHtmlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pdftohtml::Reply>> PrepareAsyncPdfToHtml(::grpc::ClientContext* context, const ::pdftohtml::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pdftohtml::Reply>>(PrepareAsyncPdfToHtmlRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends a greeting
      virtual void PdfToHtml(::grpc::ClientContext* context, const ::pdftohtml::Request* request, ::pdftohtml::Reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PdfToHtml(::grpc::ClientContext* context, const ::pdftohtml::Request* request, ::pdftohtml::Reply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pdftohtml::Reply>* AsyncPdfToHtmlRaw(::grpc::ClientContext* context, const ::pdftohtml::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pdftohtml::Reply>* PrepareAsyncPdfToHtmlRaw(::grpc::ClientContext* context, const ::pdftohtml::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status PdfToHtml(::grpc::ClientContext* context, const ::pdftohtml::Request& request, ::pdftohtml::Reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pdftohtml::Reply>> AsyncPdfToHtml(::grpc::ClientContext* context, const ::pdftohtml::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pdftohtml::Reply>>(AsyncPdfToHtmlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pdftohtml::Reply>> PrepareAsyncPdfToHtml(::grpc::ClientContext* context, const ::pdftohtml::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pdftohtml::Reply>>(PrepareAsyncPdfToHtmlRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void PdfToHtml(::grpc::ClientContext* context, const ::pdftohtml::Request* request, ::pdftohtml::Reply* response, std::function<void(::grpc::Status)>) override;
      void PdfToHtml(::grpc::ClientContext* context, const ::pdftohtml::Request* request, ::pdftohtml::Reply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::pdftohtml::Reply>* AsyncPdfToHtmlRaw(::grpc::ClientContext* context, const ::pdftohtml::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pdftohtml::Reply>* PrepareAsyncPdfToHtmlRaw(::grpc::ClientContext* context, const ::pdftohtml::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PdfToHtml_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status PdfToHtml(::grpc::ServerContext* context, const ::pdftohtml::Request* request, ::pdftohtml::Reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PdfToHtml : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PdfToHtml() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PdfToHtml() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PdfToHtml(::grpc::ServerContext* /*context*/, const ::pdftohtml::Request* /*request*/, ::pdftohtml::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPdfToHtml(::grpc::ServerContext* context, ::pdftohtml::Request* request, ::grpc::ServerAsyncResponseWriter< ::pdftohtml::Reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PdfToHtml<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_PdfToHtml : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PdfToHtml() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::pdftohtml::Request, ::pdftohtml::Reply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pdftohtml::Request* request, ::pdftohtml::Reply* response) { return this->PdfToHtml(context, request, response); }));}
    void SetMessageAllocatorFor_PdfToHtml(
        ::grpc::MessageAllocator< ::pdftohtml::Request, ::pdftohtml::Reply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pdftohtml::Request, ::pdftohtml::Reply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PdfToHtml() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PdfToHtml(::grpc::ServerContext* /*context*/, const ::pdftohtml::Request* /*request*/, ::pdftohtml::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PdfToHtml(
      ::grpc::CallbackServerContext* /*context*/, const ::pdftohtml::Request* /*request*/, ::pdftohtml::Reply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_PdfToHtml<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PdfToHtml : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PdfToHtml() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PdfToHtml() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PdfToHtml(::grpc::ServerContext* /*context*/, const ::pdftohtml::Request* /*request*/, ::pdftohtml::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PdfToHtml : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PdfToHtml() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PdfToHtml() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PdfToHtml(::grpc::ServerContext* /*context*/, const ::pdftohtml::Request* /*request*/, ::pdftohtml::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPdfToHtml(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PdfToHtml : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PdfToHtml() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PdfToHtml(context, request, response); }));
    }
    ~WithRawCallbackMethod_PdfToHtml() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PdfToHtml(::grpc::ServerContext* /*context*/, const ::pdftohtml::Request* /*request*/, ::pdftohtml::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PdfToHtml(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PdfToHtml : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PdfToHtml() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pdftohtml::Request, ::pdftohtml::Reply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pdftohtml::Request, ::pdftohtml::Reply>* streamer) {
                       return this->StreamedPdfToHtml(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PdfToHtml() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PdfToHtml(::grpc::ServerContext* /*context*/, const ::pdftohtml::Request* /*request*/, ::pdftohtml::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPdfToHtml(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pdftohtml::Request,::pdftohtml::Reply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PdfToHtml<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PdfToHtml<Service > StreamedService;
};

}  // namespace pdftohtml


#endif  // GRPC_pdftohtml_2eproto__INCLUDED
